### PR TITLE
add .bazelrc with all incompatible flags

### PR DESCRIPTION
**Pull request by aiuto**
We should start testing against the 1.0 world to find the problems now.

### CODE REVIEW

**Comment by laurentlb** [comment]
Our CI should already run the tests with the appropriate incompatible flags.

**Comment by aiuto** [comment]
> Our CI should already run the tests with the appropriate incompatible flags.

There is no CI for federation yet
Also, what Bazel does is really decoupled from federation. The only thing that matters is if the release candidate for Bazel 1.0 works with the rules we say are in the Federation. To achieve that, we need to run the federation CI with the current bazel release (not head) with all the flag flips. And it should not just be CI, it must be all development.

**Comment by laurentlb** [comment]
We're in the processed of flipping the flags for Bazel 1.0 and some of them will be removed. Using the flags in the bazelrc file means it will break at Bazel head.

In my opinion, testing the federation on the CI is very important. Do you know when it will be added?

**Comment by fweikert** [comment]
I'm working on bringing the federation to CI. We won't need the .bazelrc file since we have a separate 
"Bazelisk+incompatible flags" pipeline which will run the normal federation pipeline with the soon-to-be-flipped incompatible flags.

**Comment by aiuto** [comment]
CI should test all of the flags. That is good. It alerts us to the 1.0 release blockers. If it does them one at a time it even provides more information.
On a daily basis, though, we want to make sure that once we decide a flag can be flipped, we don't regress by ever testing without it and letting something new in.

**Pull request closed without merging**
