### PR TITLE
Update federation to skylib 1.0.2

### PR DESCRIPTION
**Pull request by aiuto**
also update federation version because that will be next release.

### CODE REVIEW

**Comment by aiuto** [comment]
Since I will be OOO, please do the merge (and delete the branch) yourself.

**Comment by aiuto** [comment]
Like python, we are testing things not included in the user distribution.

**Comment by fweikert** [comment]
Regarding your last comment: I thought about this problem while working on my pre-release distro pipeline. I think we need two sets of tests per project: 
1. a subset of all rules_foo tests that cover files in the rules_foo distro
2. "internal tests" that require the full rules_foo repo (at the commit of the rules_foo distro), tested against the distros of its dependencies

**Review by fweikert — APPROVED** [review]

**Comment by fweikert** [comment]
LGTM, I'll merge once my other PR disables the non-distro tests.

**Pull request merged**
