### PR TITLE
Update to rules_python 0.0.1

### PR DESCRIPTION
**Pull request by aiuto**
So easy....
@fweikert Please merge if you approve since I will be OOO

### CODE REVIEW

**Review by brandjon — APPROVED** [review]

**Comment by brandjon** [comment]
The CI failures are because the examples/ dir is not included in the distributable tarball, so it doesn't make sense to test them. I guess we'd have to inline the examples into the federation's own tests. This includes having the WORKSPACE under test import the appropriate dependencies, as is done by calling `rules_python_internal_deps()`.

I don't know how the federation's tests are structured, but maybe you could construct the appropriate workspace by including both a `@rules_python` repo that points to the distributable artifact, and a `@rules_python_src` repo that points to the git repository? Then maybe you can load `rules_python_internal_deps` from `@rules_python_src//internal_deps.bzl`, and test `@rules_python_src//examples/...`?

**Comment by brandjon** [comment]
> So easy....

Famous last words.

**Comment by aiuto** [comment]
We are working on rewriting the way the federation tests a rule set. There  are 2 different needs
1. test the small rules tarball in an integration test.  Do not do `bazel test @rules_python//...`
2. test the rules as if an internal test, but use a WORKSPACE built from the federation.

As I write that, I see this may be a simple solution. Imagine that rules_python is associated with a file WORKSPACE.rules_python. (We can debate about who owns it, rules or federation). The test becomes
- download the entire rules repo at the revision tag we want to test for
- replace WORKSPACE with the special WORKSPACE. This file uses the federation to bring in all deps, including the private ones needed for testing and distribution. (More or less, we have to account for rules which need some really strange rule set, but only for development, let's say an image manipulation tool used to make images for the docs - and that tool is not in the federation)
- now run `bazel test @rules_foo//...`

That procedure shows that you did not require specific versions of any rules which are in the federation.

**Comment by brandjon** [comment]
The procedure you describe is fine for running a repo's own tests against arbitrary federation releases. If we want to test the distributable tarball, using the repo's own tests (which aren't included in the tarball), then it's not so clear.

I guess in order for it to make sense to even talk about a test of the tarball, we need to be talking about integration tests that already refer to the rules by their canonical repo name. So loading `@rules_python_src` to run its `//examples` under a modified WORKSPACE that points `@rules_python` to mean the tarball makes sense I think.

**Review by fweikert — APPROVED** [review]

**Pull request merged**
